name: 📝 Code quality

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - uses: actions/checkout@v3
    - name: ⚙️ Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: ⚙️ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: 📝️ Code Scan
      run: |
        flake8 app/ --count --show-source --statistics --ignore=E501
